In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
import cartopy.crs as ccrs

In [4]:
tempMax = xr.open_dataset("/home/mlopez/EXEC/Données test/tasmax_day_BNU-ESM_rcp45_r1i1p1_na10kgrid_qm-moving-50bins-detrend_1956.nc")

In [5]:
tempMax

<xarray.Dataset>
Dimensions:       (lat: 700, lon: 1064, time: 365, ts: 3)
Coordinates:
  * ts            (ts) float32 nan nan nan
  * time          (time) object 1956-01-01 00:00:00 ... 1956-12-31 00:00:00
  * lat           (lat) float32 83.28931 83.20598 83.12265 ... 25.12497 25.04164
  * lon           (lon) float32 -141.04314 -140.9598 ... -52.54667 -52.46334
Data variables:
    time_vectors  (time, ts) int32 ...
    tasmax        (time, lat, lon) float32 ...
Attributes:
    Conventions:     CF-1.5
    title:           BNU-ESM model output prepared for CMIP5 historical
    history:         2012-03-12T06:02:50Z CMOR rewrote data to comply with CF...
    institution:     GCESS,BNU,Beijing,China
    source:          BNU-ESM\n30-day moving window 50-bins quantile mapping w...
    redistribution:  Redistribution prohibited. For internal use only.

In [6]:
tempMax.variables

Frozen({'ts': <xarray.IndexVariable 'ts' (ts: 3)>
array([nan, nan, nan], dtype=float32), 'time': <xarray.IndexVariable 'time' (time: 365)>
array([cftime.DatetimeNoLeap(1956-01-01 00:00:00),
       cftime.DatetimeNoLeap(1956-01-02 00:00:00),
       cftime.DatetimeNoLeap(1956-01-03 00:00:00), ...,
       cftime.DatetimeNoLeap(1956-12-29 00:00:00),
       cftime.DatetimeNoLeap(1956-12-30 00:00:00),
       cftime.DatetimeNoLeap(1956-12-31 00:00:00)], dtype=object)
Attributes:
    axis:           T
    long_name:      time
    standard_name:  time, 'time_vectors': <xarray.Variable (time: 365, ts: 3)>
array([[1956,    1,    1],
       [1956,    1,    2],
       [1956,    1,    3],
       ...,
       [1956,   12,   29],
       [1956,   12,   30],
       [1956,   12,   31]], dtype=int32), 'lat': <xarray.IndexVariable 'lat' (lat: 700)>
array([83.28931, 83.20598, 83.12265, ..., 25.2083 , 25.12497, 25.04164],
      dtype=float32)
Attributes:
    axis:           Y
    units:          degrees_north